import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F1F0F6",
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 58,
    paddingBottom: 120,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 28,
  },
  greeting: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    color: "#707080",
    marginBottom: 6,
  },
  userName: {
    fontSize: 24,
    fontWeight: "800",
    color: "#242424",
    letterSpacing: -0.5,
  },
  settingsButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#34345C",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  heroCard: {
    backgroundColor: "#34345C",
    borderRadius: 24,
    padding: 24,
    overflow: "hidden",
    marginBottom: 34,
    shadowColor: "#34345C",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 6,
  },
  heroDecorationOne: {
    position: "absolute",
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: "#E76F51",
    opacity: 0.15,
    top: -55,
    right: -30,
  },
  heroDecorationTwo: {
    position: "absolute",
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#F2C14E",
    opacity: 0.12,
    bottom: -40,
    left: -20,
  },
  heroIcon: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#E76F51",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  heroDescription: {
    fontSize: 14,
    lineHeight: 21,
    color: "#D9D8E2",
    maxWidth: 280,
    marginBottom: 22,
  },
  captureButton: {
    height: 52,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: "#F2C14E",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
    gap: 7,
  },
  captureButtonText: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1,
    color: "#34345C",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#242424",
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: "#707080",
  },
  seeAllText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#E76F51",
    marginBottom: 2,
  },
  emptyState: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#D9D8E2",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 30,
    marginBottom: 20,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "#F1F0F6",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#242424",
    marginBottom: 7,
  },
  emptyDescription: {
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    color: "#707080",
    maxWidth: 270,
    marginBottom: 20,
  },
  emptyButton: {
    borderWidth: 1.5,
    borderColor: "#34345C",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  emptyButtonText: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
    color: "#34345C",
  },
  statsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#D9D8E2",
    paddingVertical: 22,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statNumber: {
    fontSize: 24,
    fontWeight: "900",
    color: "#34345C",
    marginBottom: 5,
  },
  statLabel: {
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 1.2,
    color: "#707080",
  },
  statDivider: {
    width: 1,
    height: 32,
    backgroundColor: "#D9D8E2",
  },
  floatingButton: {
    position: "absolute",
    right: 22,
    bottom: 28,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#E76F51",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#242440",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  bottomSpace: {
    height: 20,
  },
});

export default styles;
