import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F1F0F6",
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 55,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 30,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  headerTextContainer: {
    flex: 1,
  },
  headerEyebrow: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.8,
    color: "#E76F51",
    marginBottom: 3,
  },
  headerTitle: {
    fontSize: 23,
    fontWeight: "800",
    color: "#242424",
  },
  headerSpacer: {
    width: 44,
  },
  previewHeader: {
    marginBottom: 20,
  },
  previewTitle: {
    fontSize: 19,
    fontWeight: "800",
    color: "#242424",
    marginBottom: 5,
  },
  previewSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    color: "#707080",
  },
  ticketContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#242440",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 7,
  },
  ticketTop: {
    backgroundColor: "#34345C",
    paddingHorizontal: 20,
    paddingVertical: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ticketBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ticketBrandText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.5,
    color: "#FFFFFF",
  },
  ticketNumber: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
    color: "#F2C14E",
  },
  ticketImageContainer: {
    height: 230,
    backgroundColor: "#D9D8E2",
  },
  ticketImage: {
    width: "100%",
    height: "100%",
  },
  noImage: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  ticketInfo: {
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 20,
  },
  ticketEventLabel: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 2,
    color: "#E76F51",
    marginBottom: 7,
  },
  ticketTitle: {
    fontSize: 27,
    fontWeight: "900",
    color: "#242424",
    letterSpacing: -0.7,
  },
  ticketDivider: {
    height: 1,
    backgroundColor: "#D9D8E2",
    marginVertical: 18,
  },
  infoRow: {
    flexDirection: "row",
  },
  infoItem: {
    flex: 1,
    paddingRight: 10,
  },
  infoLabel: {
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 1.2,
    color: "#707080",
    marginBottom: 5,
  },
  infoValue: {
    fontSize: 12,
    fontWeight: "700",
    color: "#242424",
  },
  quoteContainer: {
    marginTop: 20,
    backgroundColor: "#F1F0F6",
    borderRadius: 12,
    padding: 14,
    paddingLeft: 16,
    position: "relative",
  },
  quoteMark: {
    position: "absolute",
    top: 4,
    left: 8,
    fontSize: 28,
    fontWeight: "900",
    color: "#E76F51",
  },
  description: {
    fontSize: 13,
    lineHeight: 20,
    fontStyle: "italic",
    color: "#707080",
    paddingLeft: 8,
    paddingTop: 4,
  },
  perforationContainer: {
    height: 1,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  dashedLine: {
    width: "86%",
    borderTopWidth: 1,
    borderStyle: "dashed",
    borderColor: "#D9D8E2",
  },
  perforationCircleLeft: {
    position: "absolute",
    left: -10,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#F1F0F6",
  },
  perforationCircleRight: {
    position: "absolute",
    right: -10,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#F1F0F6",
  },
  ticketBottom: {
    paddingHorizontal: 20,
    paddingVertical: 17,
    backgroundColor: "#FAFAFC",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  admitText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.2,
    color: "#34345C",
  },
  ticketSerial: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1,
    color: "#707080",
  },
  actionsContainer: {
    marginTop: 22,
    gap: 10,
  },
  saveButton: {
    height: 56,
    borderRadius: 14,
    backgroundColor: "#34345C",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    shadowColor: "#34345C",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 5,
  },
  saveButtonText: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.4,
    color: "#FFFFFF",
  },
  editButton: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#34345C",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  editButtonText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.2,
    color: "#34345C",
  },
  footerText: {
    textAlign: "center",
    fontSize: 10,
    color: "#9A99A5",
    marginTop: 18,
  },
});

export default styles;
